# Generated by Django 4.2.16 on 2024-10-31 18:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OptionParameters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(max_length=10)),
                ('strike_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('expiry_date', models.DateField()),
                ('risk_free_rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('volatility', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='SimulationResults',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option_price', models.FloatField()),
                ('option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pricing.optionparameters')),
            ],
        ),
    ]
